# Default values for rh-sso.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  pattern: true

namespace:
  create: false

# Keycloak instance configuration
keycloak:
  replicaCount: 1
  imagePullPolicy: Always
  name: keycloak
  namespace: rhsso

database:
  imagePullPolicy: Always
# If deploying this to a production enviroment, we will need to configure an external postgres database
  # external:

sso:
  client:
    name: vp-client
  realm:
    name: vp-realm
    id: vp-realm
    enabled: true #Default true
    displayName: Validated Patterns Realm
  users:
  - userName: vp-user-dflt
    firstName: validated
    lastName: pattern
    email: validatedpatterns@redhat.com
    enabled: true #Default true
    emailVerified: false #Default false
    realmRoles: "offline_access" #Default "offline_access"
    clientRoles:
      account: "manage-account"
      realm-management: "manage-users"

#Values for external secret use

#storageClass to use with keycloak deployed postgresql
storageClassName: gp3-csi
